modLoader="javafml"
loaderVersion="[33,)"
license="MMPLv2"
issueTrackerURL="https://github.com/Pokechu22/WorldDownloader/issues/"

[[mods]]
modId="wdl"
version="4.1.0.1-SNAPSHOT"
displayName="World Downloader (Forge)"
displayURL="https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds"
authors="Pokechu22, julialy (formerly nariol, cubic72)"
description='''
World Downloader is a mod that allows making backups of Minecraft worlds.
'''

[[dependencies.wdl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="CLIENT"
